spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    password: 
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        formater-sql: true



