spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    password: 
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        formater-sql: true

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5672
    username: bpigzlwr
    password: yj-TmmnOoQJKidOOOmixkxIjYw6P61Yj
    virtual-host: bpigzlwr


mq:
  queue:
    produto-estoque-queue: produto-estoque-queue

api:
  estoque:
    url: http://localhost:8081

management:
  endpoints:
    enabled-by-default: false
    web:
        exposure:
          include: 'health,prometheus'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true



